# SPDX-License-Identifier: GPL-2.0
ARG BASE
FROM $BASE as base

RUN apt -y update -qq && DEBIAN_FRONTEND=noninteractive apt -y install \
	--no-install-recommends --no-install-suggests \
		bcftools \
		libpthread-stubs0-dev \
	&& \
	apt -y clean && rm -rf /var/lib/apt/lists/* /tmp/*

FROM base as builder

RUN apt -y update -qq && DEBIAN_FRONTEND=noninteractive apt -y install \
	--no-install-recommends --no-install-suggests \
		autoconf \
		automake \
		git \
		make \
        && \
        apt -y clean && rm -rf /var/lib/apt/lists/* /tmp/*

RUN git clone https://github.com/slowkoni/rfmix.git && \
	cd rfmix && autoreconf --force --install && ./configure && make

FROM base as runtime
ARG BASE
ARG RUN_CMD
ARG BUILD_REPO
ARG BUILD_TIME

COPY --chmod=0555 --from=builder /rfmix/rfmix /usr/local/bin/rfmix
COPY --chmod=0555 src/test/${RUN_CMD}.sh /test.sh

ENTRYPOINT [ "rfmix" ]

LABEL org.opencontainers.image.description="RFMix v2 software for local ancestry inference."
