# SPDX-License-Identifier: GPL-2.0
ARG BASE_IMAGE
FROM $BASE_IMAGE as builder

LABEL org.opencontainers.image.description="ADMIXTURE software for global ancestry calculations."

WORKDIR /ADMIXTURE
RUN wget https://dalexander.github.io/admixture/binaries/admixture_linux-1.3.0.tar.gz && \
    tar xf admixture_linux-1.3.0.tar.gz

FROM $BASE_IMAGE as runtime

ARG RUN_CMD

COPY --chmod=0555 --from=builder /ADMIXTURE/dist/admixture_linux-1.3.0/admixture /usr/local/bin/

ARG TEST="/test.sh"
COPY --chmod=0555 src/test/$RUN_CMD.sh ${TEST}
