# SPDX-License-Identifier: GPL-2.0
ARG BASE
FROM $BASE as builder

RUN apt -y update -qq && apt -y upgrade && \
        DEBIAN_FRONTEND=noninteractive apt -y install \
        --no-install-recommends --no-install-suggests \
		curl

ARG ADMIX_URL="https://dalexander.github.io/admixture/binaries/"
ARG ADMIX_BIN="admixture_linux-1.3.0.tar.gz"

WORKDIR /usr/src
RUN curl -sLO "${ADMIX_URL}/${ADMIX_BIN}" && tar xf ${ADMIX_BIN}

FROM $BASE
ARG BASE
ARG RUN_CMD

COPY --chmod=0555 --from=builder \
	/usr/src/dist/admixture_linux-1.3.0/admixture /usr/local/bin/

COPY --chmod=0555 src/test/${RUN_CMD}.sh /test.sh

ENTRYPOINT [ "admixture" ]

LABEL org.opencontainers.image.description="ADMIXTURE software for global ancestry calculations."
