# SPDX-License-Identifier: GPL-2.0
ARG BASE
FROM $BASE as builder

WORKDIR /usr/src
RUN wget https://dalexander.github.io/admixture/binaries/admixture_linux-1.3.0.tar.gz && \
    tar xf admixture_linux-1.3.0.tar.gz

FROM $BASE
ARG BASE
ARG RUN_CMD

COPY --chmod=0555 --from=builder \
	/usr/src/dist/admixture_linux-1.3.0/admixture /usr/local/bin/

COPY --chmod=0555 src/test/${RUN_CMD}.sh /test.sh

LABEL org.opencontainers.image.description="ADMIXTURE software for global ancestry calculations."
